<a href="https://www.bicajozz.hu/kerekpar-tortenete-magazin" class="button-59"><h1>Vendég</h1></a>
<img src="kepek/kezdete.jpg" style="float:left; margin-left: 10px; margin-bottom: 5px; margin-right: 10px;border: solid black 1px; padding: 2px;">
<p style="text-align: justify;">Az első kerékpár Karl von Drais báró nevéhez fűződik, aki egy szilárd vázhoz kerekeket rögzített, mivel nagyon sokat kellett járnia az erdőt, és meg akarta gyorsítani a folyamatot. Hamar rájött, hogy finomítani kell ezen a közlekedési eszközön, így az első kereket irányíthatóvá, kormányozhatóvá tette. Négy év tökéletesítés után már új kormányszerkezet és állítható ülésmagassággal rendelkezett, ekkor már (1817) az újságok is foglalkoztak a témával, bár még cinikusan.</p>
<p>Viszont utána néhány hónap leforgása alatt futótűzként terjedt el Angliában és Franciaországban.</p> 
<p>Az első valódi kerékpár megalkotójának a skót Kirkpatrick Macmillant tartják, bár ő nem fogta fel találmányának jelentőségét.</p> 
<p>Házára is ezt írták később: “Jobbat alkotott, mint amiről tudott.” Hobby Horse kerékpárjára ugyanis ingaszerű lábpedálokat szerelt, így már csak az egyensúlyozás művészetét kellett megtanulnia annak, aki ki akarta próbálni. A kovácsmester nem is kívánt hasznot húzni találmányából, nem terjesztette.</p>
<img src="kepek/kezdete1.jpg" style="float:right; margin-right: 10px; margin-bottom: 5px; margin-left: 10px;border: solid black 1px; padding: 2px;">
<p>Az első valódi kerékpár megalkotójának a skót Kirkpatrick Macmillant tartják, bár ő nem fogta fel találmányának jelentőségét. Házára is ezt írták később: “Jobbat alkotott, mint amiről tudott.” Hobby Horse kerékpárjára ugyanis ingaszerű lábpedálokat szerelt, így már csak az egyensúlyozás művészetét kellett megtanulnia annak, aki ki akarta próbálni. A kovácsmester nem is kívánt hasznot húzni találmányából, nem terjesztette.</p>
<p>A tökéletesedés egy másik problémáját R.W. Thompson találmánya, a felfújható gumibelső oldhatta volna meg. Bár szabadalmát már 1845-ben megkapta, még ’47-ben sem volt elterjedve, és emiatt az ára is igen borsos volt.</p>
<p>A francia Pierre Michaux 1861-ben alkotta meg a michauline-t, az olyan kerékpárt, aminek pedáljai az első keréken voltak. Ezzel már az egyensúlyozás is egyszerű volt, sőt, minél gyorsabban tekert az ember annál kevésbé veszíthette el az egyensúlyát. A fára vasabroncsot húztak, hogy ne kopjon olyan gyorsan. A gyártás már ’62-ben beindult, de az igazi őrület az 1867-es párizsi világkiállítás során robbant ki.</p>
<p>Közben megalakult az első kerékpárklub és megrendezték az első bicikliversenyt is. Az újítások természetesen szintén nem álltak meg. Ezek közé tartozott a golyós csapágy és a sárhányó. Rájöttek, hogy a küllők egyformán húzzák a tengelyt, így már lecserélhették a régi faküllőket nagy szakítószilárdságú acél küllőkre. Az így megszületett, a kerekeket leszámítva teljes egészében fémből készült kerékpár (Ariel) új korszakot nyitott meg.</p>